version: "3"
services:
  postgres_test:
    env_file:
      - .env.test
    image: postgres:13
    ports:
      - "33300:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/apod_bot_test/
    container_name: database_postgres_apod_test
    volumes:
      - ./database-data-test:/var/lib/postgresql/data/apod_test
