version: "3"
services:
  apod-bot:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    container_name: app_apod_bot
  postgres:
    build:
      context: "./database"
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_USER}
    container_name: database_postgres_apod
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
